### ISSUE TITLE
Rename `CollectionGenerator` to `collection::Generator`

### ISSUE THREAD

**Issue by NicMcPhee** [unhindered-ec/unhindered-ec#220]
This is only of only two remaining (as of July 2024) Clippy warnings about `module_name_repetitions`. I think it would be entirely reasonable to rename it to `Generator` and just make a habit of explicitly prefixing with `collection::Generator` if it's useful to know which kind of generator we're talking about.

Listed in #48

**Comment by JustusFluegel** [comment]
sounds good to me 👍
