### ISSUE TITLE
Run Clippy on doctests in CI

### ISSUE THREAD

**Issue by NicMcPhee** [unhindered-ec/unhindered-ec#256]
We have the ability to run Clippy on doctest code locally, but it would be nice to add the Clippy/doctest check to the CI checks as well.

A GitHub thread on the issue of running Clippy on doctests: https://github.com/rust-lang/rust/issues/56232#issuecomment-2046615285
[The `rustdoc-clippy` shell script](https://github.com/Nemo157/dotfiles/blob/74d54412ccb705551ef0c8d928d64bc9e6de69de/packages/cargo-rustdoc-clippy)

**Comment by JustusFluegel** [comment]
Closed by #257
