### ISSUE TITLE
Move away from `anyhow::Error` inside lib code

### ISSUE THREAD

**Issue by JustusFluegel** [unhindered-ec/unhindered-ec#64]
Adding explicit errors is helpful for library consumers, `anyhow::Error` doesn't really provide any indication on a programmatic level of WHY it failed,  so it becomes impossible to "catch" a specific error and recover from that. 

Maybe consider using miette for prettier diagnostics as well?

---

## Tracking

We should generate a list of sections of the code where this change needs to happen so we can mark them as completed as we work through them.

### `ec-core`

- `operator`
   - `selector`
      - [x] `Best`
      - [x] `Lexicase`
      - [x] `Random`
      - [x] `Tournament`
      - [x] `Weighted`
   - `mutator`
   - `recombinator`
   - `composable`
      - [ ] `and`
      - [ ] `map`
      - [ ] `repeat_with`
      - [ ] `then`

**Comment by NicMcPhee** [comment]
I've never use miette, but it's on my list of things it would be good to learn, so I'm fine with exploring that.

**Comment by NicMcPhee** [comment]
There's a _lot_ to do here, and I'd rather not have this end up in an enormous PR that's impossible to review. So why don't we treat this as a tracking issue, and do the work in little PRs that we record here.
